In [13]:
import tensorflow as tf
import numpy as np

Ex1

In [14]:
t = np.array([0,1,2,3,4,5,6])
print(tf.shape(t))
print(tf.rank(t))

tf.Tensor([7], shape=(1,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


Ex2

In [15]:
a  = tf.constant([[3,3]])
print(tf.shape(a))
print(tf.rank(a))

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [16]:
b = tf.constant([[2],[2]])
print(tf.shape(b))
print(tf.rank(b))

tf.Tensor([2 1], shape=(2,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [17]:
c = tf.matmul(a,b)
print(tf.shape(c))
print(tf.rank(c))

tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


np.array, np.matrix 

In [19]:
a_matrix = np.matrix([[2, 5], [1, 3], [6, 1]])
print(a_matrix)

a_array = np.array([[2, 5], [1, 3], [6, 1]])
print(a_array)


[[2 5]
 [1 3]
 [6 1]]
[[2 5]
 [1 3]
 [6 1]]


In [20]:
print(tf.shape(a_matrix))
print(tf.rank(a_matrix))
print(tf.shape(a_array))
print(tf.rank(a_array))

tf.Tensor([3 2], shape=(2,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([3 2], shape=(2,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


1X1

In [22]:
t = np.array([1])
t
k = np.array([1,2])
k

array([1, 2])

In [23]:
print(id(t))
print(tf.shape(t))
print(tf.rank(t))
print(tf.shape(k))
print(tf.rank(k))

140460162005776
tf.Tensor([1], shape=(1,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([2], shape=(1,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


2X1, 1X2

In [32]:
t1 = np.array([[1],[2],[3]])
t1
k1 = np.array([[1,2,3]])
k1

array([[1, 2, 3]])

In [33]:
print(tf.shape(t1))
print(tf.rank(t1))
print(tf.shape(k1))
print(tf.rank(k1))

tf.Tensor([3 1], shape=(2,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([1 3], shape=(2,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


2X2

In [35]:
t2 = np.array([[[1],[2]],[[3],[4]]])
print(t2)
k2 = np.array([[1,2],[3,4]])
print(k2)

[[[1]
  [2]]

 [[3]
  [4]]]
[[1 2]
 [3 4]]


In [37]:
print(tf.shape(t2))
print(tf.rank(t2))
print(tf.shape(k2))
print(tf.rank(k2))

tf.Tensor([2 2 1], shape=(3,), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([2 2], shape=(2,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


3X2

In [38]:
t3 = np.array([[[1],[2]],[[3],[4]],[[5],[6]]])
t3
k3 = np.array([[1,2],[3,4],[5,6]])
k3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
print(tf.shape(t3))
print(tf.rank(t3))
print(tf.shape(k3))
print(tf.rank(k3))

tf.Tensor([3 2 1], shape=(3,), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([3 2], shape=(2,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


2X3

In [40]:
t4 = np.array([[[1],[2],[3]],[[4],[5],[6]]])
t4
k4 = np.array([[1,2,3],[4,5,6]])
k4

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
print(tf.shape(t4))
print(tf.rank(t4))
print(tf.shape(k4))
print(tf.rank(k4))


tf.Tensor([2 3 1], shape=(3,), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


행렬(matrix) 연산

In [43]:
tf.matmul(k3,k4)

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])>

상수선언과 사칙연산

In [46]:
m_o_1 = tf.constant(42)
m_o_1
t1 = tf.constant(42)


In [47]:
print(tf.add(t1 , m_o_1))
print(tf.subtract(t1 , m_o_1))
print(tf.multiply(t1 , m_o_1))
print(tf.divide(t1, m_o_1))

tf.Tensor(84, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1764, shape=(), dtype=int32)
tf.Tensor(1.0, shape=(), dtype=float64)


Keras vs Pytorch
https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html
https://keras.io/examples/vision/mnist_convnet/


1. 패키지 불러오기

In [48]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

2. 데이터 불러오기

In [50]:
# Download training data from open datasets.
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
)


In [51]:
batch_size = 64

# Create data loaders.
train_dataloader = DataLoader(training_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size=batch_size)

for X, y in test_dataloader:
    print(f"Shape of X [N, C, H, W]: {X.shape}")
    print(f"Shape of y: {y.shape} {y.dtype}")
    break

Shape of X [N, C, H, W]: torch.Size([64, 1, 28, 28])
Shape of y: torch.Size([64]) torch.int64


3. 모델 생성하기

In [52]:
# Get cpu or gpu device for training.
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

# Define model
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10)
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = NeuralNetwork().to(device)
print(model)

Using cpu device
NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


4.모델 훈련하기

In [53]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

In [54]:
def train(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    model.train()
    for batch, (X, y) in enumerate(dataloader):
        X, y = X.to(device), y.to(device)

        # Compute prediction error
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch % 100 == 0:
            loss, current = loss.item(), batch * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

In [55]:
def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval()
    test_loss, correct = 0, 0
    with torch.no_grad():
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

In [56]:
epochs = 5
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_dataloader, model, loss_fn, optimizer)
    test(test_dataloader, model, loss_fn)
print("Done!")

Epoch 1
-------------------------------
loss: 2.305178  [    0/60000]
loss: 2.285617  [ 6400/60000]
loss: 2.271949  [12800/60000]
loss: 2.262535  [19200/60000]
loss: 2.244321  [25600/60000]
loss: 2.219320  [32000/60000]
loss: 2.219342  [38400/60000]
loss: 2.190293  [44800/60000]
loss: 2.180917  [51200/60000]
loss: 2.157293  [57600/60000]
Test Error: 
 Accuracy: 53.5%, Avg loss: 2.146200 

Epoch 2
-------------------------------
loss: 2.157610  [    0/60000]
loss: 2.141191  [ 6400/60000]
loss: 2.090470  [12800/60000]
loss: 2.103311  [19200/60000]
loss: 2.045075  [25600/60000]
loss: 1.990976  [32000/60000]
loss: 2.010234  [38400/60000]
loss: 1.935586  [44800/60000]
loss: 1.928058  [51200/60000]
loss: 1.871187  [57600/60000]
Test Error: 
 Accuracy: 57.3%, Avg loss: 1.859166 

Epoch 3
-------------------------------
loss: 1.895217  [    0/60000]
loss: 1.856292  [ 6400/60000]
loss: 1.747047  [12800/60000]
loss: 1.788120  [19200/60000]
loss: 1.668766  [25600/60000]
loss: 1.631523  [32000/600